### ISSUE TITLE
Deployment fails at installing Composer dependencies

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#191]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Install Composer Dependencies should install the dependencies.

### Actual behaviour

The stage fails. Output is: `Creating default object from empty value`

### Environment info
Operating System: Ubuntu
PHP Version: PHP 5.6.18-1+deb.sury.org~trusty+1 (cli)
Node Version: v0.10.25
Database System: MySQL
Database Version: 5.6

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by jbrooksuk** [comment]
I use the `master` version by the way.

**Comment by REBELinBLUE** [comment]
Interesting... investigating now

**Comment by jbrooksuk** [comment]
Thanks :)

**Comment by REBELinBLUE** [comment]
Which version of composer are you running on the server you are deploying to? Having trouble recreating this.

Could you try enabling `APP_DEBUG` and restarting the queue, there should be more info in the log then

**Comment by jbrooksuk** [comment]
Latest :)

**Comment by hawle** [comment]
+1
I am seeing the same problem here. I have looked at the logs, but there is no indication of the problem there. 

- Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29)
- Composer version 1.0-dev (1a5445132f1cbd366294924dc2fd0114dd4c843a) 2016-03-14 17:39:12

**Comment by jbrooksuk** [comment]
Checked the logs also, nothing useful.

**Comment by REBELinBLUE** [comment]
Hmm, this is really weird

```vagrant@web:~$ composer --version
Composer version 1.0-dev (1a5445132f1cbd366294924dc2fd0114dd4c843a) 2016-03-14 17:39:12```

Same composer version, I have `error_reporting` all the way up and `display_errors` on and I have not managed to recreate this on debian with PHP 5.6.17 nor ubuntu with PHP 7.0.3. Still investigating

**Comment by jbrooksuk** [comment]
Yeah and yeah.

**Comment by REBELinBLUE** [comment]
This is driving me mad, still can't recreate it. Can you post the `php.ini` for the CLI version of PHP for both the server Deployer is running on and the server you are deploying to?

**Comment by jbrooksuk** [comment]
Thing is, it was working previously and some projects still do work?

**Comment by REBELinBLUE** [comment]
Ah, only on certain projects. That is interesting...

**Comment by hawle** [comment]
To be honest, I have not tried further, gave it a quick reinstall, but have faced a [new issue](https://github.com/REBELinBLUE/deployer/issues/192).

**Comment by hawle** [comment]
Now, my install is perfect and clean. Still the issue is there. There are no logs. Here is the output: 

**Create New Release**
```
cd /var/www/EXAMPLE.COM
[ ! -d /var/www/EXAMPLE.COM/releases ] && mkdir /var/www/EXAMPLE.COM/releases

Extracting...

[ ! -d /var/www/EXAMPLE.COM/shared ] && mkdir /var/www/EXAMPLE.COM/shared
mkdir /var/www/EXAMPLE.COM/releases/20160316155414
cd /var/www/EXAMPLE.COM/releases/20160316155414
echo -e "\nExtracting...\n"
tar --warning=no-timestamp --gunzip --verbose --extract --file=/var/www/EXAMPLE.COM/20160316155414.tar.gz --directory=/var/www/EXAMPLE.COM/releases/20160316155414
.bowerrc
.editorconfig
.env.example
.gitattributes
.gitignore
app/
app/Console/
app/Console/Commands/
app/Console/Commands/Inspire.php
app/Console/Kernel.php
app/Events/
app/Events/Event.php
app/Exceptions/
app/Exceptions/Handler.php
app/Http/
[...]
storage/app/
storage/app/.gitignore
storage/debugbar/
storage/debugbar/.gitignore
storage/framework/
storage/framework/.gitignore
storage/framework/cache/
storage/framework/cache/.gitignore
storage/framework/sessions/
storage/framework/sessions/.gitignore
storage/framework/views/
storage/framework/views/.gitignore
storage/logs/
storage/logs/.gitignore
tests/
tests/ExampleTest.php
tests/TestCase.php
rm /var/www/EXAMPLE.COM/20160316155414.tar.gz
```

**Install Composer Dependencies**
```
[195.56.148.185]: Creating default object from empty value
Close
192.168.10.10
```

**Comment by REBELinBLUE** [comment]
Ah, interesting.

Can you edit `app/Jobs/DeployProject.php` and change line 320 from

```php
                $log->output .= $this->logError('[' . $server->ip_address . ']: ' . $e->getMessage());
```

to

```php
                $log->output .= $this->logError('[' . $server->ip_address . ']: ' . $e);
```

then restart the queue and try again, should include the full exception stack trace then rather than just the error message so I should then be able to figure out where it is happening

**Comment by hawle** [comment]
Here you go. 
```

[195.56.148.185]: exception 'ErrorException' with message 'Creating default object from empty value' in /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php:612
Stack trace:
#0 /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php(612): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Creating defaul...', '/home/vagrant/D...', 612, Array)
#1 [internal function]: REBELinBLUE\Deployer\Jobs\DeployProject->REBELinBLUE\Deployer\Jobs\{closure}('out', 'Receiving tmpfi...')
#2 /home/vagrant/Dev/deploy.dev/vendor/symfony/process/Process.php(1240): call_user_func(Object(Closure), 'out', 'Receiving tmpfi...')
#3 /home/vagrant/Dev/deploy.dev/vendor/symfony/process/Process.php(1327): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('out', 'Receiving tmpfi...')
#4 /home/vagrant/Dev/deploy.dev/vendor/symfony/process/Process.php(364): Symfony\Component\Process\Process->readPipes(true, true)
#5 /home/vagrant/Dev/deploy.dev/vendor/symfony/process/Process.php(203): Symfony\Component\Process\Process->wait()
#6 /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php(614): Symfony\Component\Process\Process->run(Object(Closure))
#7 /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php(637): REBELinBLUE\Deployer\Jobs\DeployProject->sendFile('/home/vagrant/D...', '/var/www/litho....', Object(REBELinBLUE\Deployer\Server))
#8 /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php(450): REBELinBLUE\Deployer\Jobs\DeployProject->sendFileFromString(Object(REBELinBLUE\Deployer\Server), '/var/www/litho....', 'APP_ENV=product...')
#9 /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php(280): REBELinBLUE\Deployer\Jobs\DeployProject->getScript(Object(REBELinBLUE\Deployer\DeployStep), Object(REBELinBLUE\Deployer\Server), Object(REBELinBLUE\Deployer\ServerLog))
#10 /home/vagrant/Dev/deploy.dev/app/Jobs/DeployProject.php(103): REBELinBLUE\Deployer\Jobs\DeployProject->runStep(Object(REBELinBLUE\Deployer\DeployStep))
#11 [internal function]: REBELinBLUE\Deployer\Jobs\DeployProject->handle()
#12 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(82): Illuminate\Container\Container->call(Array)
#14 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(REBELinBLUE\Deployer\Jobs\DeployProject))
#15 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(REBELinBLUE\Deployer\Jobs\DeployProject))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(REBELinBLUE\Deployer\Jobs\DeployProject))
#17 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(REBELinBLUE\Deployer\Jobs\DeployProject))
#18 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(83): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(41): Illuminate\Bus\Dispatcher->dispatchNow(Object(REBELinBLUE\Deployer\Jobs\DeployProject))
#20 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#21 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(53): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#22 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(210): Illuminate\Queue\Jobs\BeanstalkdJob->fire()
#23 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), '1', 0)
#24 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'deployer-high,d...', 0, '3', '1')
#25 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(87): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'deployer-high,d...', 0, '3', '1')
#26 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(104): Illuminate\Queue\Worker->daemon(NULL, 'deployer-high,d...', 0, 128, '3', '1')
#27 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(72): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'deployer-high,d...', 0, 128, true)
#28 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#29 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#30 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#31 /home/vagrant/Dev/deploy.dev/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/vagrant/Dev/deploy.dev/vendor/symfony/console/Application.php(844): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/vagrant/Dev/deploy.dev/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/vagrant/Dev/deploy.dev/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/vagrant/Dev/deploy.dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /home/vagrant/Dev/deploy.dev/artisan(46): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}
```

**Comment by hawle** [comment]
Looking at your trace, it seems the issue is in DeployProject.php:600. 

You are using $log variable in the $process->run method, but you are not handling the case if $log is null. 
In line 637, you are calling sendFile method without the $log variable.

**Comment by REBELinBLUE** [comment]
Thanks, yeah I see the problem, fixing it right now

**Comment by REBELinBLUE** [comment]
Fixed, sorry about that

**Comment by jbrooksuk** [comment]
Awesome, thanks!

**Comment by hawle** [comment]
No problem, thanks for fixing it so quickly!

Should we checkout master, or wait for new tag?

**Comment by jbrooksuk** [comment]
I've checked out master, but it still seems to be showing the same error.

**Comment by REBELinBLUE** [comment]
Uh... I assume you restarted the queue?

**Comment by jbrooksuk** [comment]
I didn't, but I'll try that tomorrow.

**Comment by REBELinBLUE** [comment]
Ah OK. the bug was in the queue job, normally the `artisan app:update` command restarts the queue

**Comment by jbrooksuk** [comment]
Still an issue here :(

**Comment by REBELinBLUE** [comment]
Hmm. Could you do the same thing as https://github.com/REBELinBLUE/deployer/issues/191#issuecomment-197393047 ? Wondering if there is another PHP error which I've missed

**Comment by REBELinBLUE** [comment]
@jbrooksuk did you get a chance to try this?

**Comment by jbrooksuk** [comment]
Hey @REBELinBLUE sorry I missed this, I managed to cancel the notification and then forgot about it,

I've just updated to `master`, restarted the queue and everything works. Thanks :+1:

**Comment by REBELinBLUE** [comment]
Ah, no worries, good to hear! Thanks :)
