### ISSUE TITLE
cronjob error "Too many arguments."

### ISSUE THREAD

**Issue by chiendv** [REBELinBLUE/deployer#255]
Hi,
My cronjob geting this error when run.

[Symfony\Component\Console\Exception\RuntimeException]
  Too many arguments.

### Environment info
Operating System: CentOs
PHP Version: 7.0.9 
Node Version: 2.1.3
Database System: mysql
Database Version:
QUEUE_DRIVER=redis
Socket: Node

### Logs (see storage/logs/) or other output that would be helpful
```
[2016-07-27 22:22:01] production.ERROR: Symfony\Component\Console\Exception\RuntimeException: Too many arguments. in /home/dp/public_html/deployer/vendor/symfony/console/Input/ArgvInput.php:179
Stack trace:
#0 /home/dp/public_html/deployer/vendor/symfony/console/Input/ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('1')
#1 /home/dp/public_html/deployer/vendor/symfony/console/Input/Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#2 /home/dp/public_html/deployer/vendor/symfony/console/Command/Command.php(224): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 /home/dp/public_html/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/dp/public_html/deployer/vendor/symfony/console/Application.php(844): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/dp/public_html/deployer/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Console\Scheduling\ScheduleRunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/dp/public_html/deployer/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/dp/public_html/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/dp/public_html/deployer/artisan(45): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
```

**Comment by REBELinBLUE** [comment]
hmm, odd. What do you have the cronjob command set to?

**Comment by chiendv** [comment]
here it is:

/usr/bin/php70 /home/dp/public_html/deployer/artisan schedule:run 1

**Comment by REBELinBLUE** [comment]
It is the 1 which is causing the problem, that shouldn't be there, I assume you took it from

https://github.com/REBELinBLUE/deployer/blob/master/examples/crontab

the `1>>` at the end is for redirecting all output to /dev/null
