### ISSUE TITLE
node socket.js can't start！

### ISSUE THREAD

**Issue by PowellMao** [REBELinBLUE/deployer#287]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [0.0.39 ] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [7.0.7 ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ YES] You've ran `composer install --no-dev` from the root of your installation.
- [YES ] You've ran `npm install --production` from the root of your installation.
- [ NO] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [NO ] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

*Please describe what you're expecting to see happen.*

### Actual behaviour

**WEB site：**
 Server error

A connection could not be established to the socket at http://deployer.app. This is required for reporting the status on running deployments. Please reload, if the issue continues please contact the system administrator

**[root@deployer deployer]# node socket.js**

[WARN] Redis server does not require a password, but a password was supplied.
/home/wwwroot/deployer/socket.js:89
    if (message.event.indexOf('RestartSocketServer') !== -1) {
                     ^

TypeError: Cannot read property 'indexOf' of undefined
    at Redis.<anonymous> (/home/wwwroot/deployer/socket.js:89:22)
    at emitThree (events.js:116:13)
    at Redis.emit (events.js:194:7)
    at Redis.exports.returnReply (/home/wwwroot/deployer/node_modules/ioredis/lib/redis/parser.js:123:14)
    at JavascriptReplyParser.returnReply (/home/wwwroot/deployer/node_modules/ioredis/lib/redis/parser.js:28:13)
    at JavascriptReplyParser.run (/home/wwwroot/deployer/node_modules/redis-parser/lib/javascript.js:137:18)
    at JavascriptReplyParser.execute (/home/wwwroot/deployer/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/home/wwwroot/deployer/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

### Environment info
Operating System: Centos 7
PHP Version: 7.0.7
Node Version: v6.9.1
Database System:Mysql
Database Version:5.7.11

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
Hmm, weird; looking into it now. I will need to provision a centos VM first so will take a little while.

Do you have a `REDIS_PASSWORD=` line in `.env` ? if so can you try removing it?

**Comment by PowellMao** [comment]
need install supervisor and Beanstalkd.
start supervisor 
[root@deployer deployer]#  ps -ef|grep node
root      6793  6788  0 14:10 ?        00:00:01 node socket.js

**Comment by REBELinBLUE** [comment]
Sorry? The installer should warn you if beanstalk is missing, but beanstalk isn't used by the `socket.js` server and supervisor is only used to reset it if it dies
