### ISSUE TITLE
Got a exception when the queue is running as daemon

### ISSUE THREAD

**Issue by iflamed** [REBELinBLUE/deployer#98]
I think this is because of the daemon, we need reconnect the database before we running a new job.
Here is the exception log:

```php
[2015-09-19 14:17:40] local.ERROR: exception 'ErrorException' with message 'Error while sending STMT_PREPARE packet. PID=12995' in /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php:310
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Error while sen...', '/www/sites/depl...', 310, Array)
#1 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php(310): PDO->prepare('select * from `...')
#2 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#3 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php(596): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#4 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php(315): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#5 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1389): Illuminate\Database\Connection->select('select * from `...', Array, true)
#6 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1379): Illuminate\Database\Query\Builder->runSelect()
#7 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1364): Illuminate\Database\Query\Builder->getFresh(Array)
#8 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(409): Illuminate\Database\Query\Builder->get(Array)
#9 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(168): Illuminate\Database\Eloquent\Builder->getModels(Array)
#10 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(140): Illuminate\Database\Eloquent\Builder->get(Array)
#11 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(87): Illuminate\Database\Eloquent\Builder->first(Array)
#12 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(119): Illuminate\Database\Eloquent\Builder->find(2, Array)
#13 [internal function]: Illuminate\Database\Eloquent\Builder->findOrFail(2)
#14 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3423): call_user_func_array(Array, Array)
#15 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(65): Illuminate\Database\Eloquent\Model->__call('findOrFail', Array)
#16 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(65): REBELinBLUE\Deployer\SharedFile->findOrFail(2)
#17 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(40): REBELinBLUE\Deployer\Events\ModelCreated->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#18 [internal function]: REBELinBLUE\Deployer\Events\ModelCreated->__wakeup()
#19 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(40): unserialize('O:40:"REBELinBL...')
#20 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Broadcasting\BroadcastEvent->fire(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#21 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(53): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#22 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\BeanstalkdJob->fire()
#23 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), '1', 0)
#24 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '3', '1')
#25 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(87): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, 0, '3', '1')
#26 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(103): Illuminate\Queue\Worker->daemon(NULL, NULL, 0, 128, '3', '1')
#27 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, true)
#28 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#29 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#30 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#31 /www/sites/deployer/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /www/sites/deployer/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /www/sites/deployer/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /www/sites/deployer/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(100): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /www/sites/deployer/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}

Next exception 'Illuminate\Database\QueryException' with message 'Error while sending STMT_PREPARE packet. PID=12995 (SQL: select * from `shared_files` where `shared_files`.`deleted_at` is null and `shared_files`.`id` = 2 limit 1)' in /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php:636
Stack trace:
#0 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php(596): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php(315): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1389): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1379): Illuminate\Database\Query\Builder->runSelect()
#4 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1364): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(409): Illuminate\Database\Query\Builder->get(Array)
#6 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(168): Illuminate\Database\Eloquent\Builder->getModels(Array)
#7 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(140): Illuminate\Database\Eloquent\Builder->get(Array)
#8 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(87): Illuminate\Database\Eloquent\Builder->first(Array)
#9 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(119): Illuminate\Database\Eloquent\Builder->find(2, Array)
#10 [internal function]: Illuminate\Database\Eloquent\Builder->findOrFail(2)
#11 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3423): call_user_func_array(Array, Array)
#12 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(65): Illuminate\Database\Eloquent\Model->__call('findOrFail', Array)
#13 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(65): REBELinBLUE\Deployer\SharedFile->findOrFail(2)
#14 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(40): REBELinBLUE\Deployer\Events\ModelCreated->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#15 [internal function]: REBELinBLUE\Deployer\Events\ModelCreated->__wakeup()
#16 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(40): unserialize('O:40:"REBELinBL...')
#17 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Broadcasting\BroadcastEvent->fire(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#18 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(53): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#19 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\BeanstalkdJob->fire()
#20 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), '1', 0)
#21 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '3', '1')
#22 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(87): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, 0, '3', '1')
#23 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(103): Illuminate\Queue\Worker->daemon(NULL, NULL, 0, 128, '3', '1')
#24 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, true)
#25 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#26 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#27 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#28 /www/sites/deployer/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /www/sites/deployer/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /www/sites/deployer/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /www/sites/deployer/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(100): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /www/sites/deployer/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}  
```

**Comment by iflamed** [comment]
I will fix this now.

**Comment by REBELinBLUE** [comment]
Ah, never had it happen myself, although had it with another app which runs as a daemon. Thanks I will merge the pull request tomorrow evening

**Comment by iflamed** [comment]
I got this on my new server.  I will check again after you merged.

发自 刘兵 的 iPhone
